version: "3.7"

services:

  backend:
    image: sispheor/radiogaga-back
    volumes:
      - /tmp/static:/code/static
      - ${PWD}/radiogaga_db:/code/db
    devices:
      - /dev/snd:/dev/snd # audio control
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: sispheor/radiogaga-front
    ports:
      - "80:80"
    volumes:
      - /tmp/static:/static
    depends_on:
      - backend
    restart: always
